---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anomaly-detector
  namespace: istio-system
  labels:
    app: anomaly-detector
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anomaly-detector
      version: v2
  template:
    metadata:
      labels:
        app: anomaly-detector
        version: v2
    spec:
      containers:
      - name: anomaly-detector
        image: rafatrevisan/anomaly_detector:latest
        imagePullPolicy: Always
        env:
        - name: PROMETHEUS_ADDRESS
          value: prometheus
        - name: PROMETHEUS_PORT
          value: '9090'
        - name: KNN_NEIGHBORS
          value: '5'
        - name: WAIT_SEC
          value: '1'
        ports:
        - name: exporter
          containerPort: 9090
          protocol: TCP
        - name: tcp
          containerPort: 80
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: anomaly-detector
  namespace: istio-system
  labels:
    app: anomaly-detector
    service: anomaly-detector
spec:
  ports:
  - port: 9090
    name: http
  selector:
    app: anomaly-detector
